# Generated by Django 2.1.2 on 2018-10-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functional_completeness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'Функция', 'verbose_name_plural': 'Функции'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Обьект', 'verbose_name_plural': 'Обьекты'},
        ),
        migrations.RemoveField(
            model_name='object',
            name='functions',
        ),
        migrations.AddField(
            model_name='function',
            name='objects_list',
            field=models.ManyToManyField(blank=True, related_name='functions', to='functional_completeness.Object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='object',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_list', to='functional_completeness.Group', verbose_name='Группа'),
        ),
    ]
