# Generated by Django 2.1.2 on 2018-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functional_completeness', '0002_auto_20181016_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='e_g',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='group',
            name='e_h',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='group',
            name='e_p',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='e_s',
            field=models.FloatField(default=0.1),
        ),
    ]
