# Generated by Django 2.1.2 on 2018-12-11 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functional_completeness', '0003_auto_20181017_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='e_g',
            field=models.FloatField(default=0.5, verbose_name='Eg'),
        ),
        migrations.AlterField(
            model_name='group',
            name='e_h',
            field=models.FloatField(default=0.6, verbose_name='Eh'),
        ),
        migrations.AlterField(
            model_name='group',
            name='e_p',
            field=models.FloatField(default=1, verbose_name='Ep'),
        ),
        migrations.AlterField(
            model_name='group',
            name='e_s',
            field=models.FloatField(default=0.1, verbose_name='Es'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('group', 'name')},
        ),
    ]
