# Generated by Django 2.1.2 on 2018-10-15 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('url', models.CharField(help_text='Name из массива urlpatterns', max_length=100, unique=True, validators=[django.core.validators.URLValidator()], verbose_name='Имя url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Метод',
                'verbose_name_plural': 'Методы',
            },
        ),
    ]
