# Generated by Django 2.1.2 on 2018-12-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_auto_20181016_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='url',
            field=models.CharField(help_text='Name из массива urlpatterns', max_length=100, unique=True, verbose_name='Модуль метода'),
        ),
    ]
