# Generated by Django 2.1.2 on 2018-12-11 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
                'ordering': ('poll', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
                'ordering': ('poll', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='puro.Poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ('poll', 'number'),
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='puro.Poll', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='expert',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='puro.Poll', verbose_name='Опрос'),
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together={('poll', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('poll', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='expert',
            unique_together={('poll', 'name')},
        ),
    ]
