# Generated by Django 2.1.2 on 2018-12-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puro', '0002_auto_20181211_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='number',
        ),
    ]
