# Generated by Django 2.1.2 on 2018-12-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puro', '0003_remove_tour_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertIndicatorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='puro.Expert', verbose_name='Эксперт')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='puro.Indicator', verbose_name='Показатель')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='puro.Tour', verbose_name='Тур')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='expertindicatororder',
            unique_together={('tour', 'expert', 'indicator')},
        ),
    ]
